spring:
  profiles:
    active: dev
    include:
      - base-addi
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver

#  batch:
#    job:
#      names:
#      enabled:
  logging:
    level:
      root: info
      com.ll.exam.final__2022_10_08.app: debug
      org.hibernate.type.descriptor.sql: trace
  custom:
    order:
      cancelAvailableSeconds: 600
    rebate:
      wholesalePriceRate: 0.5
    site:
      name: T-BOOKS
      baseUrl: "http://localhost:8080"
